CREATE TABLE airport_review
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id              VARCHAR(30)                             NOT NULL,
    content                  VARCHAR(300)                            NOT NULL,
    description              VARCHAR(300),
    delete_flag              BOOLEAN DEFAULT FALSE                   NOT NULL,
    created_at               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by               VARCHAR(255)                            NOT NULL,
    updated_by               VARCHAR(255)                            NOT NULL,
    version                  BIGINT                                  NOT NULL,
    airport_id               VARCHAR(255),
    airport_reivew_parent_id BIGINT,
    CONSTRAINT pk_airport_review PRIMARY KEY (id)
);

CREATE TABLE airport_review_emotions
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    count             NUMERIC(20, 0) DEFAULT 0                NOT NULL,
    description       VARCHAR(300),
    delete_flag       BOOLEAN        DEFAULT FALSE            NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by        VARCHAR(255)                            NOT NULL,
    updated_by        VARCHAR(255)                            NOT NULL,
    version           BIGINT                                  NOT NULL,
    airport_review_id BIGINT                                  NOT NULL,
    emotion_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_airport_review_emotions PRIMARY KEY (id)
);

CREATE TABLE emotions
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(300),
    delete_flag  BOOLEAN DEFAULT FALSE                   NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by   VARCHAR(255)                            NOT NULL,
    updated_by   VARCHAR(255)                            NOT NULL,
    version      BIGINT                                  NOT NULL,
    emotion_id   VARCHAR(30)                             NOT NULL,
    emotion_name VARCHAR(300)                            NOT NULL,
    emotion_url  VARCHAR(300)                            NOT NULL,
    CONSTRAINT pk_emotions PRIMARY KEY (id)
);

CREATE TABLE plane_review_emotions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    count           NUMERIC(20, 0) DEFAULT 0                NOT NULL,
    description     VARCHAR(300),
    delete_flag     BOOLEAN        DEFAULT FALSE            NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    updated_by      VARCHAR(255)                            NOT NULL,
    version         BIGINT                                  NOT NULL,
    plane_review_id BIGINT                                  NOT NULL,
    emotion_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_plane_review_emotions PRIMARY KEY (id)
);

CREATE TABLE plane_reviews
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id            VARCHAR(30)                             NOT NULL,
    content                VARCHAR(300)                            NOT NULL,
    description            VARCHAR(300),
    delete_flag            BOOLEAN DEFAULT FALSE                   NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by             VARCHAR(255)                            NOT NULL,
    updated_by             VARCHAR(255)                            NOT NULL,
    version                BIGINT                                  NOT NULL,
    plane_id               VARCHAR(30)                             NOT NULL,
    plane_review_parent_id BIGINT,
    CONSTRAINT pk_plane_reviews PRIMARY KEY (id)
);

ALTER TABLE emotions
    ADD CONSTRAINT uc_emotions_emotion UNIQUE (emotion_id);

ALTER TABLE emotions
    ADD CONSTRAINT uc_emotions_emotion_name UNIQUE (emotion_name);

ALTER TABLE airport_review_emotions
    ADD CONSTRAINT FK_AIRPORT_REVIEW_EMOTIONS_ON_AIRPORT_REVIEW FOREIGN KEY (airport_review_id) REFERENCES airport_review (id);

ALTER TABLE airport_review_emotions
    ADD CONSTRAINT FK_AIRPORT_REVIEW_EMOTIONS_ON_EMOTION FOREIGN KEY (emotion_id) REFERENCES emotions (id);

ALTER TABLE airport_review
    ADD CONSTRAINT FK_AIRPORT_REVIEW_ON_AIRPORT_REIVEW_PARENT FOREIGN KEY (airport_reivew_parent_id) REFERENCES airport_review (id);

ALTER TABLE plane_reviews
    ADD CONSTRAINT FK_PLANE_REVIEWS_ON_PLANE_REVIEW_PARENT FOREIGN KEY (plane_review_parent_id) REFERENCES plane_reviews (id);

ALTER TABLE plane_review_emotions
    ADD CONSTRAINT FK_PLANE_REVIEW_EMOTIONS_ON_EMOTION FOREIGN KEY (emotion_id) REFERENCES emotions (id);

ALTER TABLE plane_review_emotions
    ADD CONSTRAINT FK_PLANE_REVIEW_EMOTIONS_ON_PLANE_REVIEW FOREIGN KEY (plane_review_id) REFERENCES plane_reviews (id);