-- v1: initializes the tables for schedule service.

-- Create table "airports"
CREATE TABLE airports
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description     VARCHAR(300),
    delete_flag     BOOLEAN DEFAULT FALSE                   NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    updated_by      VARCHAR(255)                            NOT NULL,
    version         BIGINT                                  NOT NULL,
    airport_id      VARCHAR(30)                             NOT NULL,
    airport_name    VARCHAR(200)                            NOT NULL,
    airport_state   VARCHAR(200)                            NOT NULL,
    airport_country VARCHAR(200)                            NOT NULL,
    CONSTRAINT pk_airports PRIMARY KEY (id)
);

-- Create table "gates"
CREATE TABLE gates
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(300),
    delete_flag BOOLEAN DEFAULT FALSE                   NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  VARCHAR(255)                            NOT NULL,
    updated_by  VARCHAR(255)                            NOT NULL,
    version     BIGINT                                  NOT NULL,
    gate_code   VARCHAR(30)                             NOT NULL,
    terminal_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_gates PRIMARY KEY (id)
);

-- Create table "schedule_details"
CREATE TABLE schedule_details
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description       VARCHAR(300),
    delete_flag       BOOLEAN DEFAULT FALSE                   NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by        VARCHAR(255)                            NOT NULL,
    updated_by        VARCHAR(255)                            NOT NULL,
    version           BIGINT                                  NOT NULL,
    schedule_id       BIGINT                                  NOT NULL,
    point_stop        INTEGER                                 NOT NULL,
    airport_id        BIGINT                                  NOT NULL,
    estimated_arrival TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    distance_km       BIGINT                                  NOT NULL,
    CONSTRAINT pk_schedule_details PRIMARY KEY (id)
);

-- Create table "schedules"
CREATE TABLE schedules
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description    VARCHAR(300),
    delete_flag    BOOLEAN DEFAULT FALSE                   NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by     VARCHAR(255)                            NOT NULL,
    updated_by     VARCHAR(255)                            NOT NULL,
    version        BIGINT                                  NOT NULL,
    plane_id       VARCHAR(30)                             NOT NULL,
    check_in_date  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    onboard_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    departure_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    gate_id        BIGINT                                  NOT NULL,
    status         INTEGER DEFAULT 1                       NOT NULL,
    CONSTRAINT pk_schedules PRIMARY KEY (id)
);

-- Create table "terminals"
CREATE TABLE terminals
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description   VARCHAR(300),
    delete_flag   BOOLEAN DEFAULT FALSE                   NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by    VARCHAR(255)                            NOT NULL,
    updated_by    VARCHAR(255)                            NOT NULL,
    version       BIGINT                                  NOT NULL,
    terminal_code VARCHAR(30)                             NOT NULL,
    terminal_name VARCHAR(200)                            NOT NULL,
    airport_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_terminals PRIMARY KEY (id)
);

ALTER TABLE airports
    ADD CONSTRAINT uc_airports_airport UNIQUE (airport_id);

ALTER TABLE gates
    ADD CONSTRAINT FK_GATES_ON_TERMINAL FOREIGN KEY (terminal_id) REFERENCES terminals (id);

ALTER TABLE schedules
    ADD CONSTRAINT FK_SCHEDULES_ON_GATE FOREIGN KEY (gate_id) REFERENCES gates (id);

ALTER TABLE schedule_details
    ADD CONSTRAINT FK_SCHEDULE_DETAILS_ON_AIRPORT FOREIGN KEY (airport_id) REFERENCES airports (id);

ALTER TABLE schedule_details
    ADD CONSTRAINT FK_SCHEDULE_DETAILS_ON_SCHEDULE FOREIGN KEY (schedule_id) REFERENCES schedules (id);

ALTER TABLE terminals
    ADD CONSTRAINT FK_TERMINALS_ON_AIRPORT FOREIGN KEY (airport_id) REFERENCES airports (id);