CREATE TABLE user_roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(300),
    delete_flag BOOLEAN DEFAULT FALSE                   NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  VARCHAR(255)                            NOT NULL,
    updated_by  VARCHAR(255)                            NOT NULL,
    version     BIGINT                                  NOT NULL,
    code        VARCHAR(30)                             NOT NULL,
    role_name   VARCHAR(200)                            NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (id)
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(300),
    delete_flag  BOOLEAN DEFAULT FALSE                   NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by   VARCHAR(255)                            NOT NULL,
    updated_by   VARCHAR(255)                            NOT NULL,
    version      BIGINT                                  NOT NULL,
    user_id      VARCHAR(30)                             NOT NULL,
    first_name   VARCHAR(50)                             NOT NULL,
    last_name    VARCHAR(50)                             NOT NULL,
    sex          BOOLEAN                                 NOT NULL,
    address      VARCHAR(400),
    birth_date   date                                    NOT NULL,
    phone_number VARCHAR(30)                             NOT NULL,
    avatar       VARCHAR(255),
    email        VARCHAR(200)                            NOT NULL,
    username     VARCHAR(100)                            NOT NULL,
    password     VARCHAR(100)                            NOT NULL,
    verify       BOOLEAN DEFAULT FALSE                   NOT NULL,
    role_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE user_roles
    ADD CONSTRAINT uc_user_roles_code UNIQUE (code);

ALTER TABLE user_roles
    ADD CONSTRAINT uc_user_roles_role_name UNIQUE (role_name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone_number UNIQUE (phone_number);

ALTER TABLE users
    ADD CONSTRAINT uc_users_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES user_roles (id);